INSERT INTO SHAIN VALUES('admin','admin','アドミン','001','1');
INSERT INTO SHAIN VALUES('test','test','テスト','002','0');
INSERT INTO SHAIN VALUES('son','son','孫','003','1');
INSERT INTO SHAIN VALUES('user','user','ユーザー','004','1');

INSERT INTO ROLES VALUES('admin','ADMIN');
INSERT INTO ROLES VALUES('admin','USER');
INSERT INTO ROLES VALUES('son','ADMIN');
INSERT INTO ROLES VALUES('son','USER');
INSERT INTO ROLES VALUES('user','USER');
INSERT INTO ROLES VALUES('test','USER');
