DROP TABLE TEST_MODEL IF EXISTS;

CREATE TABLE TEST_MODEL(NO VARCHAR(20) NOT NULL primary key,NAME VARCHAR(20));

INSERT INTO TEST_MODEL(NO, NAME) VALUES (1, 'son');
INSERT INTO TEST_MODEL(NO, NAME) VALUES (2, 'kim');
