DROP TABLE SHAIN;
DROP TABLE ROLES;

CREATE TABLE SHAIN (
	SHAIN_ID VARCHAR(20) NOT NULL PRIMARY KEY,
	PASSWORD VARCHAR(35) NOT NULL,
	SHAIN_MEI VARCHAR(50),
	SHAIN_BANGO VARCHAR(5),
	ENABLE CHAR(1)
);

CREATE TABLE ROLES (
	SHAIN_ID VARCHAR(20) NOT NULL,
	ROLE VARCHAR(10) NOT NULL,
	CONSTRAINT FK_ROLE_SHAIN FOREIGN KEY(SHAIN_ID) REFERENCES SHAIN(SHAIN_ID)
);

INSERT INTO SHAIN VALUES('admin','admin','アドミン','001','1');
INSERT INTO SHAIN VALUES('test','test','テスト','002','0');
INSERT INTO SHAIN VALUES('son','son','孫','003','1');
INSERT INTO SHAIN VALUES('user','user','ユーザー','004','1');

INSERT INTO ROLES VALUES('admin','ADMIN');
INSERT INTO ROLES VALUES('admin','USER');
INSERT INTO ROLES VALUES('son','ADMIN');
INSERT INTO ROLES VALUES('son','USER');
INSERT INTO ROLES VALUES('user','USER');
INSERT INTO ROLES VALUES('test','USER');
