-- iContact DDL
-- USERS
CREATE TABLE USERS
(
    ACCOUNT VARCHAR(30),
    PASSWORD VARCHAR(30) NOT NULL,
	USERNAME VARCHAR(30) NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY(ACCOUNT)
);

-- CONTACTS
CREATE TABLE CONTACTS
(
    NAME VARCHAR(30),
    PHONE VARCHAR(20),
    EMAIL VARCHAR(50),
    ADDRESS VARCHAR(200),
    NOTES VARCHAR(500),
    STATUS CHAR(1),         --  O:SYNC, A:ADD M:MODIFY, D:DELETE
    ACCOUNT VARCHAR(30),
    CONSTRAINT PK_CONTACTS PRIMARY KEY(NAME),
    CONSTRAINT FK_CONTACTS FOREIGN KEY(ACCOUNT) REFERENCES USERS(ACCOUNT)
);

