-- DDL

DROP TABLE SHAIN;
DROP TABLE ROLES;

-- 社員
CREATE TABLE SHAIN (
	SHAIN_ID 		VARCHAR(20) NOT NULL PRIMARY KEY,
	PASSWORD 		VARCHAR(35) NOT NULL,
	SHAIN_MEI 		VARCHAR(50),
	SHAIN_BANGO 	VARCHAR(5),
	ENABLE 			CHAR(1)
);

-- 権限
CREATE TABLE ROLES (
	SHAIN_ID 	VARCHAR(20) NOT NULL,
	ROLE 		VARCHAR(10) NOT NULL,
	CONSTRAINT FK_ROLE_SHAIN FOREIGN KEY(SHAIN_ID) REFERENCES SHAIN(SHAIN_ID)
);

-- 申請
CREATE TABLE SHINSEI (
	SHINSEI_BANGO 	VARCHAR(14),
	SHAIN_ID 		VARCHAR(20),
	SHINSEI_KUBUN 	VARCHAR(2),
	SHINSEI_JOKYO 	VARCHAR(2) DEFAULT '01',	--申請完了
	SHINSEI_FILE 	CLOB
);

-- 勤務表
CREATE TABLE KINMUHYO (
	SHINSEI_BANGO 			VARCHAR(14),
	NENGETSU 				VARCHAR(7),
	SHINSEI_JOKYO 			VARCHAR(2),
	SYOTEI_NISSU 			NUMBER,
	KEKKIN_NISSU 			NUMBER,
	JITSUDO_JIKAN_GOKEI 	NUMBER,
	SAGYO_GENBA 			VARCHAR(50)
)

-- 勤務表詳細
CREATE TABLE KINMUHYO_SHOSAI (
	SHINSEI_BANGO 		VARCHAR(14),
	NENGETSU 			VARCHAR(7),
	HIZUKE 				VARCHAR(5),
	YASUMI_KUBUN 		VARCHAR(2) DEFAULT '00',	--無し
	SHIGYO_JIKAN		VARCHAR(5),
	SHIGYO_JIKANCHI 	NUMBER,
	SYURYO_JIKAN		VARCHAR(5),
	SYURYO_JIKANCHI 	NUMBER,
	KYUKEI_JIKAN		NUMBER,
	JITSUDO_JIKAN		NUMBER,
	SAGYO_NAIYO			VARCHAR(500)
)

-- DML

INSERT INTO SHAIN VALUES('admin','admin','アドミン','001','1');
INSERT INTO SHAIN VALUES('test','test','テスト','002','0');
INSERT INTO SHAIN VALUES('son','son','孫','003','1');
INSERT INTO SHAIN VALUES('user','user','ユーザー','004','1');

INSERT INTO ROLES VALUES('admin','ADMIN');
INSERT INTO ROLES VALUES('admin','USER');
INSERT INTO ROLES VALUES('son','ADMIN');
INSERT INTO ROLES VALUES('son','USER');
INSERT INTO ROLES VALUES('user','USER');
INSERT INTO ROLES VALUES('test','USER');

COMMIT;
