DROP TABLE USERINFO IF EXISTS;
DROP TABLE AUTHORITIES IF EXISTS;
DROP TABLE EMPLOYEE IF EXISTS;

CREATE TABLE USERINFO (
	USERNAME       VARCHAR(50)         NOT NULL PRIMARY KEY,
	PASSWORD       VARCHAR(50)         NOT NULL,
	ENABLED        INT                 DEFAULT '0' NOT NULL
);

CREATE TABLE AUTHORITIES (
    USERNAME        VARCHAR(12) NOT NULL,
    AUTHORITY       VARCHAR(20) NOT NULL
);

CREATE TABLE EMPLOYEE
(
    EMP_NAME                        VARCHAR(64),
    PASSWORD 						VARCHAR(64),
    EMAIL                           VARCHAR(64)
);

INSERT INTO USERINFO VALUES ('admin', 'admin', 1);
INSERT INTO USERINFO VALUES ('user', 'user', 1);
INSERT INTO USERINFO VALUES ('son', 'son', 1);
INSERT INTO USERINFO VALUES ('kim', 'kim', 0);

INSERT INTO AUTHORITIES VALUES ('admin', 'ROLE_ADMIN');
INSERT INTO AUTHORITIES VALUES ('admin', 'ROLE_USER');
INSERT INTO AUTHORITIES VALUES ('user', 'ROLE_USER');
INSERT INTO AUTHORITIES VALUES ('son', 'ROLE_ADMIN');
INSERT INTO AUTHORITIES VALUES ('son', 'ROLE_USER');
INSERT INTO AUTHORITIES VALUES ('kim', 'ROLE_USER');

INSERT INTO EMPLOYEE VALUES ('admin','admin','admin@gmail.com');
INSERT INTO EMPLOYEE VALUES ('user','user','user@gmail.com');
INSERT INTO EMPLOYEE VALUES ('son','son','son@gmail.com');
