DROP TABLE FLORA;

--CREATE DATABASE FLORA;
--GRANT ALL PRIVILEGES ON flora.* TO mysql@localhost IDENTIFIED BY 'mysql' WITH GRANT OPTION;

--USE FLORA;

CREATE TABLE IF NOT EXISTS FLORA(
	ID INT(5) NOT NULL UNIQUE,
	FLORAID VARCHAR(20),
	PASSWORD VARCHAR(20),
	NAME VARCHAR(20),
	EMAIL VARCHAR(20),
	JOB VARCHAR(20),
	BIRTHDAY DATE
);