DROP TABLE IF EXISTS ATTACHMENT;
DROP TABLE IF EXISTS ARTICLE;

CREATE TABLE ARTICLE (
    ID INT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT TEXT NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE ATTACHMENT (
    ID INT NOT NULL AUTO_INCREMENT,
    ARTICLEID INT NOT NULL,
    FILENAME VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(ARTICLEID) REFERENCES ARTICLE(ID)
);
