DROP TABLE IF EXISTS PUBLIC.SHAIN;
DROP TABLE IF EXISTS PUBLIC.ROLES;
DROP TABLE IF EXISTS PUBLIC.SHINSEI;
DROP TABLE IF EXISTS PUBLIC.KINMUHYO;
DROP TABLE IF EXISTS PUBLIC.KINMUHYO_SYOSAI;
DROP SEQUENCE IF EXISTS seq_shain_id;

CREATE SEQUENCE IF NOT EXISTS seq_shain_id
START WITH 1
INCREMENT BY 1;

CREATE TABLE SHAIN (
    SHAIN_ID        INT NOT NULL DEFAULT seq_shain_id.nextval PRIMARY KEY,
    PASSWORD        VARCHAR2(35) NOT NULL,
    SHAIN_MEI       VARCHAR2(50),
    SHAIN_BANGO     VARCHAR2(5),
    ENABLE          CHAR(1),
    ROLE            VARCHAR2(1)
);
CREATE TABLE ROLES (
    SHAIN_ID    INT NOT NULL,
    ROLE        VARCHAR2(10) NOT NULL,
    CONSTRAINT FK_ROLE_SHAIN FOREIGN KEY(SHAIN_ID) REFERENCES SHAIN(SHAIN_ID)
);
CREATE TABLE SHINSEI (
    SHINSEI_BANGO   VARCHAR2(14),
    SHAIN_BANGO     VARCHAR2(5),
    SHINSEI_KUBUN   VARCHAR2(2),
    SHINSEI_JOKYO   VARCHAR2(2) DEFAULT '01', 
    SHINSEI_FILE    CLOB,
    SHINSEI_KEKKA   INT
);
CREATE TABLE KINMUHYO (
    SHINSEI_BANGO           VARCHAR2(14),
    SHINSEI_KUBUN           VARCHAR2(2),
    NENGETSU                VARCHAR2(7),
    SHINSEI_JOKYO           VARCHAR2(2),
    SYOTEI_NISSU            NUMBER,
    SAGYO_NISSU             NUMBER,
    KEKKIN_NISSU            NUMBER,
    JITSUDO_JIKAN_GOKEI     NUMBER,
    SAGYO_GENBA             VARCHAR2(50)
);
CREATE TABLE KINMUHYO_SYOSAI (
    SHINSEI_BANGO       VARCHAR2(14),
    NENGETSU            VARCHAR2(7),
    HIZUKE              VARCHAR2(5),
    YASUMI_KUBUN        VARCHAR2(2) DEFAULT '00',
    SHIGYO_JIKAN        VARCHAR2(5),
    SHIGYO_JIKANCHI     NUMBER,
    SYURYO_JIKAN        VARCHAR2(5),
    SYURYO_JIKANCHI     NUMBER,
    KYUKEI_JIKAN        NUMBER,
    JITSUDO_JIKAN       NUMBER,
    SAGYO_NAIYO         VARCHAR2(500)
);

INSERT INTO SHAIN (PASSWORD,SHAIN_MEI,SHAIN_BANGO,ENABLE,ROLE)
VALUES
('admin','admin','001','1','1'),
('test','test','002','0','0'),
('son','son','003','1','0'),
('user','user','004','1','0');