--DROP TABLE AUTHORITIES;
--DROP TABLE USERINFO;

CREATE TABLE USERINFO(
  USERID VARCHAR(20) PRIMARY KEY,
  PASSWORD VARCHAR(20),
  NAME VARCHAR(100),
  EMAIL VARCHAR(50),
  ENABLED BOOLEAN NOT NULL
);

CREATE TABLE AUTHORITIES (
    USERID VARCHAR(50) NOT NULL,
    AUTHORITY VARCHAR(50) NOT NULL
);

CREATE UNIQUE INDEX IX_AUTH_USERNAME ON AUTHORITIES (USERID, AUTHORITY);

ALTER TABLE AUTHORITIES ADD CONSTRAINT FK_AUTHORITIES_USERINFO FOREIGN KEY (USERID) REFERENCES USERINFO;
