
/* [1] 그룹추가 */
INSERT INTO GROUPS(GROUP_NAME) VALUES ('Users');
INSERT INTO GROUPS(GROUP_NAME) VALUES ('Administrators');

/* [2] 역할을 그룹에 할당 */
INSERT INTO GROUP_AUTHORITIES (GROUP_ID, AUTHORITY) 
	SELECT ID, 'ROLE_USER'
	FROM   GROUPS 
	WHERE  GROUP_NAME = 'Users';
INSERT INTO GROUP_AUTHORITIES (GROUP_ID, AUTHORITY) 
	SELECT ID, 'ROLE_USER'
	FROM   GROUPS 
	WHERE  GROUP_NAME = 'Administrators';
INSERT INTO GROUP_AUTHORITIES (GROUP_ID, AUTHORITY) 
	SELECT ID, 'ROLE_ADMIN'
	FROM   GROUPS 
	WHERE  GROUP_NAME = 'Administrators';

/* [3] 사용자생성 */
INSERT INTO USERS VALUES('admin','admin','administrator','admin@gmail.com', true);
INSERT INTO USERS VALUES('user','user','seungbeomi','son@gmail.com', true);

/* [4] 사용자를 그룹지정 */
INSERT INTO GROUP_MEMBERS(GROUP_ID, USERNAME)
	SELECT ID, 'user'
	FROM GROUPS
	WHERE GROUP_NAME = 'Users';
INSERT INTO GROUP_MEMBERS(GROUP_ID, USERNAME)
	SELECT ID, 'admin'
	FROM GROUPS
	WHERE GROUP_NAME = 'Administrators';
