SELECT M.GRAND_TOTAL, M.COMMUTATION_TOTAL, M.BIZ_FARE_TOTAL, M.REG_SEASON_TICKET_TOTAL, T.FARE,  M.REG_OTHERS_TOTAL, M.REGULAR_TOTAL, M.IRREGULLAR_TOTAL
	FROM TRAFFIC_EXPENSES_MONTH M, TRAFFIC_KIND T
	WHERE EMP_NO = 'R258' AND YM = '200910'


INSERT INTO TRAFFIC_KIND
	VALUES('R258','200910','B',1,'洋光台','神谷町',TO_DATE('20091001','YYYYMMDD'), TO_DATE('20091031', 'YYYYMMDD'), 'FILENAME', 25000, 'CODE', 210, 180,'S111', CURRENT_TIMESTAMP)

SELECT FARE,
	CASE DIVISION WHEN 'B' THEN 'バス' END
FROM TRAFFIC_KIND
WHERE EMP_NO = 'R258' AND YM = '200910'



SELECT M.GRAND_TOTAL, M.COMMUTATION_TOTAL, M.BIZ_FARE_TOTAL, M.REG_SEASON_TICKET_TOTAL, T.FARE,  M.REG_OTHERS_TOTAL, M.REGULAR_TOTAL, M.IRREGULLAR_TOTAL
	FROM TRAFFIC_EXPENSES_MONTH M, (SELECT FARE, EMP_NO FROM TRAFFIC_KIND WHERE EMP_NO = 'R258' AND YM = '200910' AND DIVISION = 'B') T
	WHERE M.EMP_NO = T.EMP_NO
		AND M.EMP_NO = 'R258'
		AND M.YM = '200910'

INSERT INTO TRAFFIC_EXPENSES_MONTH(EMP_NO,YM,APPR_STATUS,REG_SEASON_TICKET_TOTAL,REG_BUS_TOTAL,REG_OTHERS_TOTAL,REGULAR_TOTAL,IRREGULLAR_TOTAL,COMMUTATION_TOTAL,BIZ_TRAFFIC_TOTAL,BIZ_HOTEL_TOTAL,BIZ_FARE_TOTAL,GRAND_TOTAL,LAST_MONTH_GRAND_TOTAL,MODIFIER_ID,MODIFIED_DATE)
VALUES ('R258','200909','O',1000,500,500,2000,1000,3000,300,100,400,3400,0,'孫承範',CURRENT_TIMESTAMP)


INSERT INTO TRAFFIC_EXPENSES_MONTH(EMP_NO,YM,APPR_STATUS,REG_SEASON_TICKET_TOTAL,REG_BUS_TOTAL,REG_OTHERS_TOTAL,REGULAR_TOTAL,IRREGULLAR_TOTAL,COMMUTATION_TOTAL,BIZ_TRAFFIC_TOTAL,BIZ_HOTEL_TOTAL,BIZ_FARE_TOTAL,GRAND_TOTAL,LAST_MONTH_GRAND_TOTAL,MODIFIER_ID,MODIFIED_DATE)
VALUES ('R258','200910','X','2000','1000','500','3500','1200','4700','1300','1100','2400','7100','3000','R999',CURRENT_TIMESTAMP)

INSERT INTO TRAFFIC_EXPENSES_DAY (EMP_NO, YM, YMD, DIVISION, DAY_OF_WEEK, TRAIN_FARE, TRAIN_SECTION, BUS_FARE, BUS_SECTION, OTHER_REG_FARE, OTHER_REG_REM, OTHER_IRREG_FARE, OTHER_IRREG_REM, TAXI_FARE, HOTEL_RATE, REM, MODIFIER_ID, MODIFIED_DATE)
VALUES ('R258', '200910', TO_DATE('20091001', 'YYYYMMDD'), '0', '4', 560, 'yoho-kami', 180, 'yokou-yoko', 0, '', 0, '', 0, 0, 'bikou', 'son', CURRENT_TIMESTAMP)

INSERT INTO TRAFFIC_KIND (EMP_NO, YM, DIVISION, TRAFFIC_SEQ, DEPARTURE_POINT, ARRIVAL_POINT, START_DATE,END_DATE, FILE_NAME, FARE, BUS_CARD_CD, ONE_WAY_FARE_ON_CARD, ONE_WAY_FARE_REAL, MODIFIER_ID, MODIFIED_DATE)
VALUES ('R258', '200910', 'B', '1111', 'YOKOUDAI', 'YOKOHAMA', TO_DATE('20091001', 'YYYMMDD'), TO_DATE('20091031','YYYMMDD'), 'FILE_PATH', 200, '1010', 100, 86, 'son', CURRENT_TIMESTAMP);
