-- 社員
CREATE TABLE SHAIN (
	SHAIN_ID VARCHAR(20) NOT NULL PRIMARY KEY,
	PASSWORD VARCHAR(35) NOT NULL,
	SHAIN_MEI VARCHAR(50),
	SHAIN_BANGO VARCHAR(5),
	ENABLE CHAR(1)
);

-- 権限
CREATE TABLE ROLES (
	SHAIN_ID VARCHAR(20) NOT NULL,
	ROLE VARCHAR(10) NOT NULL,
	CONSTRAINT FK_ROLE_SHAIN FOREIGN KEY(SHAIN_ID) REFERENCES SHAIN(SHAIN_ID)
);

-- 受信ファイル
CREATE TABLE JUSHIN_FILE (
	SHINSEI_BANGO VARCHAR(14),
	SHINSEI_FILE LONGVARCHAR
);

-- 申請
create table SHINSEI (
	SHINSEI_BANGO VARCHAR(14),
	SHINSEI_JOKYO CHAR(2)
);

-- 勤務表
--CREATE TABLE KINMUHYO (
--)
