-- 社員
CREATE TABLE SHAIN (
	SHAIN_ID 		VARCHAR(20) NOT NULL PRIMARY KEY,
	PASSWORD 		VARCHAR(35) NOT NULL,
	SHAIN_MEI 		VARCHAR(50),
	SHAIN_BANGO 	VARCHAR(5),
	ENABLE 			CHAR(1)
);

-- 権限
CREATE TABLE ROLES (
	SHAIN_ID 	VARCHAR(20) NOT NULL,
	ROLE 		VARCHAR(10) NOT NULL,
	CONSTRAINT FK_ROLE_SHAIN FOREIGN KEY(SHAIN_ID) REFERENCES SHAIN(SHAIN_ID)
);

-- 申請
CREATE TABLE SHINSEI (
	SHINSEI_BANGO 	VARCHAR(14)		PRIMARY KEY,
	SHAIN_ID 		VARCHAR(20),
	SHINSEI_KUBUN 	VARCHAR(2),
	SHINSEI_JOKYO 	VARCHAR(2) 		DEFAULT '01',	--申請完了
	SHINSEI_FILE 	LONGVARCHAR,
	SHINSEI_KEKKA 	LONGVARCHAR
);

-- 勤務表
CREATE TABLE KINMUHYO (
	SHINSEI_BANGO 			VARCHAR(14),
	NENGETSU 				VARCHAR(7),
	SHINSEI_JOKYO 			VARCHAR(2),
	SYOTEI_NISSU 			DOUBLE,
	KEKKIN_NISSU 			DOUBLE,
	JITSUDO_JIKAN_GOKEI 	DOUBLE,
	SAGYO_GENBA 			VARCHAR(50)
);

-- 勤務表詳細
CREATE TABLE KINMUHYO_SHOSAI (
	SHINSEI_BANGO 		VARCHAR(14),
	NENGETSU 			VARCHAR(7),
	HIZUKE 				VARCHAR(5),
	YASUMI_KUBUN 		VARCHAR(2) DEFAULT '00',	--無し
	SHIGYO_JIKAN		VARCHAR(5),
	SHIGYO_JIKANCHI 	DOUBLE,
	SYURYO_JIKAN		VARCHAR(5),
	SYURYO_JIKANCHI 	DOUBLE,
	KYUKEI_JIKAN		DOUBLE,
	JITSUDO_JIKAN		DOUBLE,
	SAGYO_NAIYO			VARCHAR(500)
);

