DROP TABLE EMP_DETAIL;
DROP TABLE EMP;
DROP TABLE DEPT;

CREATE TABLE DEPT (
	DEPT_NO VARCHAR(20) PRIMARY KEY,
	DEPT_NAME VARCHAR(50)
);

CREATE TABLE EMP (
	EMP_NO VARCHAR(20) PRIMARY KEY,
	EMP_NAME VARCHAR(50),
	DEPT_NO VARCHAR(20) REFERENCES DEPT(DEPT_NO)
);

CREATE TABLE EMP_DETAIL (
	EMP_NO VARCHAR(20) REFERENCES EMP(EMP_NO),
	EMAIL VARCHAR(50)
);

INSERT INTO DEPT VALUES ('D001','DEVELOPMENT');
INSERT INTO DEPT VALUES ('D002','NETWORK');

INSERT INTO EMP VALUES ('E001','son','D001');
INSERT INTO EMP VALUES ('E002','kim','D001');
INSERT INTO EMP VALUES ('E003','lee','D002');

INSERT INTO EMP_DETAIL VALUES ('E001', 'seungbeomi@gmail.com');
INSERT INTO EMP_DETAIL VALUES ('E002', 'administrator@gmail.com');

SELECT * FROM DEPT;
SELECT * FROM EMP;
SELECT * FROM EMP_DETAIL;